version: "3.8"

services:
  db:
    image: postgres:15
    container_name: todo_app_v3_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - todo_app_v3_postgres_data:/var/lib/postgresql/data

volumes:
  todo_app_v3_postgres_data:
